# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '20201130-MVVM-Fipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 20201130-MVVM-Fipe
	pod 'Alamofire'

  target '20201130-MVVM-FipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '20201130-MVVM-FipeUITests' do
    # Pods for testing
  end

end
