# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_FIPE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_FIPE
  pod 'Alamofire'

  target 'MVVM_FIPETests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM_FIPEUITests' do
    # Pods for testing
  end

end
